[package]
name = "beeplancer"
edition = "2024.beta"

[dependencies]
# Dependencies are automatically managed by the 2024.beta edition
# No need to explicitly include Sui framework here

[addresses]
beeplancer = "0x0"
